### ISSUE TITLE
Subsequent elements are ignored with "once: true"

### ISSUE THREAD

**Issue by Jugibur** [codeAbinash/scroll-observer#1]
Hi, 
if I set "once: true" in the options, my subsequent animations are not executed.
Tried our options with "onshow" / "onhide" with console messages.

**Comment by codeAbinash** [comment]
Thank you for creating this issue. I got that problem. 
In the next commit it will be fixed.

**Comment by codeAbinash** [comment]
Now it is fixed (v1.0.3), now you can close this issue.
Once again, thanks a lot 🧑🏻‍💻.

**Comment by Jugibur** [comment]
Great, thanks too!
